### ISSUE TITLE
Advanced API queries

### ISSUE THREAD

**Issue by smlmbrt** [PGScatalog/pgscatalog_utils#1]
Download all scores by:
- Trait using an EFO id (`/rest/trait/{trait_id}`)
- Publication using aPGP id (`/rest/publication/{pgp_id}`)

Rest documentation: [https://www.pgscatalog.org/rest/#/](https://www.pgscatalog.org/rest/#/)

**Comment by nebfield** [comment]
44c487799e525706daf080062c90794303fc64f7
