### ISSUE TITLE
Check if scoring files are in PGS Catalog format with JSON schema

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgscatalog_utils#10]
`combine_scorefiles` should check that input files meet the PGS Catalog standard to detect if custom scoring files are able to be combined with PGS Catalog data

**Comment by smlmbrt** [comment]
@ens-lgil do we have anything that would do this already?

**Comment by ens-lgil** [comment]
Not really. 
We use `pandas_schema` (from the GWAS validator):
https://github.com/PGScatalog/pgs_scoringfile_validator/blob/master/validator/validate/schema.py

**Comment by ens-lgil** [comment]
However, including the different PGS scoring file validators into pgscatalog_utils would make sense.

**Comment by smlmbrt** [comment]
> However, including the different PGS scoring file validators into pgscatalog_utils would make sense.

I think it would make sense to explore including them as a validation module within this package?

**Comment by ens-lgil** [comment]
Potentially something close to what we have currently here for the harmonized files: https://github.com/ens-lgil/pgs_harmonizedfile_validator
And we can include/integrate the validator of the formatted scoring files

**Comment by smlmbrt** [comment]
Related functionality added in #22
