### ISSUE TITLE
Add summary log to combine_scorefiles

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgscatalog_utils#14]
Log should contain information about the scoring files that were included in the final combined file with information extracted from the PGS Catalog style-header:

- [ ] Original genome build per scoring file
- [ ] Original number of variants 
- [ ] Traits
- [ ] PGS Name
- [ ] Citation
- [ ] Which columns were used, variant sources, harmonisation status

**Comment by smlmbrt** [comment]
Duplicated by #24
