### ISSUE TITLE
Profile and reduce memory usage in `match_variants`

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgscatalog_utils#21]
![Figure_1](https://user-images.githubusercontent.com/11425618/191752984-7e24d764-777f-497f-9139-d5ed9efb54c3.png)

**Comment by nebfield** [comment]
Improvements implemented in #20 
<img width="377" alt="Screenshot 2022-10-04 at 15 34 31" src="https://user-images.githubusercontent.com/11425618/193847876-200be1b8-247c-4f60-9ce8-9b1f40ed9dae.png">

**Comment by smlmbrt** [comment]
Implemented in #26
