### ISSUE TITLE
Adapt combine_scorefiles to output information from scoring file headers

### ISSUE THREAD

**Issue by smlmbrt** [PGScatalog/pgscatalog_utils#24]
`combine_scorefiles` already reads headers as a dictionary. The information extracted from the PGS Catalog style-header should be combined into a log/json file indexed by the scoring file accession that includes:

- [ ] Original genome build per scoring file
- [ ] Original number of variants 
- [ ] Traits
- [ ] PGS Name
- [ ] Citation
- [ ] Which columns were used, variant sources, harmonisation status

Changes will need to be made to `pgsc_calc` to use metadata from the json rather than an API call. This will have the added benefit of not requiring internet access for any step of the pipeline after `download_scorefiles`. Changes needed:

- [ ] [`modules/local/score_report.nf`](https://github.com/PGScatalog/pgsc_calc/blob/4952d2139ce4f6b5d5e590cc1a995de33c950dd5/modules/local/score_report.nf) 
- [ ] [`bin/report.Rmd`](https://github.com/PGScatalog/pgsc_calc/blob/db0cad2fd2e64b17c1339c8640a02dbd765528f7/bin/report.Rmd)

**Comment by smlmbrt** [comment]
@ens-lgil is this something you could take on?

**Comment by ens-lgil** [comment]
Yes, I can have a look at it
