### ISSUE TITLE
Replace home-brewed batching with `read_csv_batched`

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgscatalog_utils#34]
Polars added native support for batched CSV reading

https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_csv_batched.html

**Comment by smlmbrt** [comment]
Would implementing this be better/more stable long term?

**Comment by nebfield** [comment]
[Batched reads now implemented in the new repo](https://github.com/PGScatalog/pygscatalog/blob/main/pgscatalog.match/src/pgscatalog/match/lib/_arrow.py).
