### ISSUE TITLE
Validate downloaded scoring files with checksum

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgscatalog_utils#35]

**Comment by smlmbrt** [comment]
This seems worthwhile and also helpful for versioning. @ens-lgil are you good to take this on?

**Comment by ens-lgil** [comment]
I am writing a script to generate all the md5 files on the FTP

**Comment by smlmbrt** [comment]
Is that something we'd hold in the DB/API as a type of score versioning?
