### ISSUE TITLE
Refactor to a namespace package

### ISSUE THREAD

**Issue by nebfield** [PGScatalog/pgscatalog_utils#49]
It would be better to package this collection of useful programs as a namespace package.

This would improve our ability to re-use code as a proper library for new projects. Multiple distribution packages makes it simpler to install smaller programs or parts of the utilities package.

https://packaging.python.org/en/latest/guides/packaging-namespace-packages/

**Comment by smlmbrt** [comment]
Does this just change the structure of the package? Is there still only one poetry lockfile, etc?

**Comment by nebfield** [comment]
Implemented in: 

https://github.com/PGScatalog/pygscatalog

There's now four python packages which all get installed inside the `pgscatalog` namespace 🚀
