### ISSUE TITLE
Make sure ancestry_analysis works on single samples 

### ISSUE THREAD

**Issue by smlmbrt** [PGScatalog/pgscatalog_utils#57]
@AWS-crafter are you by any chance running the pipeline on a single sample?

_Originally posted by @smlmbrt in https://github.com/PGScatalog/pgsc_calc/issues/177#issuecomment-1737035019_

Current fails on the Mann-whitney U test stage when there is only 1 sample

**Comment by AWS-crafter** [comment]
Thanks for looking into this. I've previously ran the pipeline successfully with --run_ancestry on a single sample, so having 1 sample probably is not sufficient in and of itself to cause a failure, but does under certain circumstances (i.e, single sample + some other unknown factor).

**Comment by smlmbrt** [comment]
Also mentioned here https://github.com/PGScatalog/pgsc_calc/issues/174#issuecomment-1775321744

**Comment by smlmbrt** [comment]
> Thanks for looking into this. I've previously ran the pipeline successfully with --run_ancestry on a single sample, so having 1 sample probably is not sufficient in and of itself to cause a failure, but does under certain circumstances (i.e, single sample + some other unknown factor).

This is helpful to know!

**Comment by smlmbrt** [comment]
This bug might not actually be specific to single-samples (re: https://github.com/PGScatalog/pgsc_calc/issues/177#issuecomment-1804847942)

**Comment by smlmbrt** [comment]
#65 will likely fix this bug that happens when there are only samples with numeric identifiers.

**Comment by nebfield** [comment]
https://github.com/PGScatalog/pgscatalog_utils/releases/tag/v0.4.3
